configfile: "config.yaml"

from pathlib import Path

batches = [f"batch_{i:03}" for i in range(662)]
assemblies_dir = Path(config["assemblies_dir"])
kmer_size = int(config["k"])


rule all:
    input: [f"output/kmer_matches/{batch}.counts.txt" for batch in batches]


rule count_kmers:
    input:
        assembly_batch=f"{assemblies_dir}/{{batch}}",
        reads=config["reads"]
    output:
        kmer_counts = "output/kmer_matches/{batch}.counts.txt"
    conda:
        "envs/jellyfish.yaml"
    shadow: "shallow"
    params:
        k=kmer_size
    script: "scripts/count_kmers.py"
