name: mof-search test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_build:
    name: Build and test linux
    if: ${{ contains(github.event.head_commit.message, 'Run CI') }}
    runs-on: ubuntu-20.04
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.7"

    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba=0.20.0
        /usr/bin/env python3 -m pip install snakemake==6.2.0

    - name: Check out code for the build
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test
      run: |
        rm queries/backbone19Kbp.fa
        make test

  mac_build:
    name: Build and test Mac OS X
    if: ${{ contains(github.event.head_commit.message, 'Run CI') }}
    runs-on: macos-11
    steps:
    - uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: "3.7"

    - name: Install dependencies
      run: |
        conda install -c conda-forge mamba=0.20.0
        /usr/bin/env python3 -m pip install snakemake==6.2.0

    - name: Check out code for the build
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Test
      run: |
        rm queries/backbone19Kbp.fa
        make test

